---
- name: RSH into toolbox pod Updated
  shell: >
      oc exec {{ ceph_toolbox_pod_name }}
  run_once: true

- name: Check the full ratio
  shell: >
       oc exec {{ ceph_toolbox_pod_name }} 'ceph pg dump | grep -i full'
  register: full_ratio

- name: Increase FULL ratio
  shell: >
    oc exec {{ ceph_toolbox_pod_name }} 'ceph pg set_full_ratio 0.97'
  run_once: true

- name: Verify if full ration is set to 97%
  shell: >
      oc exec {{ ceph_toolbox_pod_name }} 'ceph pg dump | grep -i full'
  run_once: increased_full_ratio

- name:  Delete the Unused PVC and PV
  shell: >
    oc delete pvc "{{ item }}"
  loop:
    - "{{ pvc_list }}"

- name: Delete the unused PV
  shell: >
    oc delete pv "{{ item }}"
  loop:
    - "{{ pv_list }}"
  run_once: true

- name: Resetting back to original ratio
  shell: >
      oc exec {{ ceph_toolbox_pod_name }} 'ceph pg set_full_ratio 0.95'
  run_once: true
